### ISSUE TITLE
How about a non-mutable @byrow macro?

### ISSUE THREAD

**Issue by dldx** [JuliaData/DataFramesMeta.jl#108]
Perhaps I'm missing something but there doesn't seem to be a way to run @byrow! without changing the original dataframe. This makes it a little awkward to preview changes to the dataframe in advance.

Is it possible to have a @byrow macro as well?

**Comment by nalimilan** [comment]
Indeed. I'm not sure why `@byrow!` is the only mutating function of the API. It's also weird that `@newcol` inside it does not affect the original data frame.

@tshort Do you remember why it works that way?

**Comment by tshort** [comment]
As to why `@byrow!` is mutating, but `@newcol` does not affect the original dataframe, it's mainly to have the least impact. Copying columns is often expensive, so that's avoided by mutating. Creating a new dataframe with existing columns is fairly inexpensive, so that's why that is done in combination with `@newcol`. It's analogous to `d2 = copy(d); d2[:newcol] = 3`. `d` doesn't have the new column, but `d` and `d2` still share `d`'s original columns, so changes to those affect both dataframes.

The naming of `@byrow!` is a bit tricky. It started out as just `@byrow`. I'm not sure the name change was a good idea because the macro itself does not do any mutating. It's only when you assign within the macro block that you get mutation. The name was changed to act as a reminder that mutation is possible within the block. It's not unique within DataFramesMeta, though. `@with` also enables mutation. Here is an example:

```julia
julia> d = DataFrame(a = rand(3), b = rand(1:2, 3))
3×2 DataFrame
│ Row │ a         │ b │
├─────┼───────────┼───┤
│ 1   │ 0.883709  │ 1 │
│ 2   │ 0.0595057 │ 1 │
│ 3   │ 0.843765  │ 2 │

julia> @with(d, :a .= 9);

julia> d
3×2 DataFrame
│ Row │ a   │ b │
├─────┼─────┼───┤
│ 1   │ 9.0 │ 1 │
│ 2   │ 9.0 │ 1 │
│ 3   │ 9.0 │ 2 │
```

If you don't want mutation, you can always do `@byrow! deepcopy(df) ...`. It'd be easy to add a `@byrow` macro that did this automatically. A better version could look for assignment and only copy those columns--that's tricky though as there's different ways to assign, and might be tricky to catch them all. Overall, I don't think the addition of a nonmutating `@byrow` offers much.

**Comment by tshort** [comment]
If you're not mutating, you'll be copying data. If it's just for exploration, you could operate on a subset of the data (also a copy). If you only want to copy the columns affected, then that'd be a bigger change to the macro.

**Comment by nalimilan** [comment]
R uses copy-on-write a lot (that's the only way for it to avoid making thousands of copies), but we use a much more explicit approach: you copy the data manually if you don't want to mutate it. (I guess we could internally implement copy-on-write as an optimization, but that shouldn't affect the user-visible behavior.)

I'd say it would make sense to have two versions of each macro: one mutating with the `!` suffix (which would allow adding columns to the original data frame), and one equivalent to calling `copy(df)`. It wouldn't copy the columns themselves (so you could still mutate them), but at least an assignment to a column would create a new vector. That way at least things like `:a = :b .* 2` in `@byrow` wouldn't affect the original data frame. Does that make sense?

Then there's the additional complexity that `df2 = copy(df); df2[:x] = df2[:x] .* 2` does *not* mutate `df[:x]`, but `df2[:x] = 2` and `df2[:x] .= 2` do. Not sure what to do about that in the context of DataFramesMeta.

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaData/DataFramesMeta.jl/pull/154.
