### ISSUE TITLE
[Deprecation] groupby

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/DataFramesMeta.jl#116]
```
data = DataFrame(Subject = categorical(repeat(1:24, inner = 2)),
                 Sequence = categorical(repeat(1:4, inner = 12)),
                 Period = categorical(repeat(1:2, 24)),
                 AUC = rand(48)) |>
       groupby(:Subject)
```

**Comment by pdeffebach** [comment]
The offending code for this is actually in DataFrames [here](https://github.com/JuliaData/DataFrames.jl/blob/5824b6ba02809f6ab4ba1453dfa3bd8e9adfd259/src/deprecated.jl#L1330).

**Comment by nalimilan** [comment]
Is this supposed to work?

**Comment by nalimilan** [comment]
Ah, got it, the problem is the deprecation as in https://github.com/JuliaData/DataFramesMeta.jl/issues/115. Would you make a PR to remove that particular deprecation?

**Comment by Nosferican** [comment]
Made the PR at DataFrames. The decision here would then be whether DataFramesMeta should incorporate the one-argument flavored functions DataFrames had.
```
df = df |> (df -> sort!(df)) |> ...
```
or
```
df = df |> sort! |> ...
```
I can make a separate issue for that discussion.

**Comment by pdeffebach** [comment]
Actually, I can replicate some weird behavior with `@linq` 

Given that the `@linq` macro works with `df` as the first argument, it's nice to be able to write anonymous functions for other positions. Unfortunately, it doesn't work out quite like that, instead returning the anonymous function itself. 



```
df = DataFrame(rand(5,5))

julia> @linq df |>
       transform(t = :x1) |>
       (x -> (x.y = 5))
#18 (generic function with 1 method)

julia> @linq df |>
       transform(t = :x1) |>
       x -> x.y = 5
#23 (generic function with 1 method)

julia> function foo(h, df)
       df.y = 5
       end
foo (generic function with 1 method)

julia> @linq df |>
       transform(t = :x1) |>
       (x -> foo(5, x))
#28 (generic function with 1 method)
```

I thought the problem might be solved using Lazy's `@>` macro. and indeed it is, to an extent. 

```
julia> @> df @transform(t = :x1) (x -> (x.y = 5))
```

returns `5`. This is actually the correct behavior, with two caveats. 

1) With the recent changes in `setindex` [#1571](https://github.com/JuliaData/DataFrames.jl/pull/1571) you will no longer be able to run the code `x.y = 5` because we will deprecate the automatic broadcasting. (Side note: this is going to break a ton of things in DataFramesMeta so if I have time i will try and make a branch with the set/getindex PRs)
2) The fact that `setindex` returns whatever is being set is fine, because its consistent with `setindex` everywhere else, but it definitely counts as a gotcha in the context of piping. 

Two avenues to explore: 1) What is `Lazy.@>` doing that is making anonymous functions work so well and 2) what kinds of best practices could be clarified, if any, about using anonymous functions with pipes.
