### ISSUE TITLE
@orderby in reverse

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFramesMeta.jl#166]
Is it possible to achieve? Looking through the code, it doesn't seem like it's possible.

**Comment by pdeffebach** [comment]
Thanks for the issue report. Yes this does seem feasible. 

DataFrames has a cool struct called `order` for specifying whether or not to go in a different order. 

```
  julia> sort(df, order(:x, rev=true))
```

it also has a `rev = true` keyword argument. 

Looking at `@orderby` it seems to have a lot of weird behavior. 

1. It applies to both `DataFrame`s and `GroupedDataFrame`s, but has different behavior. The first functions like `DataFrames.sort` while the second sorts the groups in a grouped data frame, which I don't think has a function in DataFrames currently. These should be split into two functions. 

2. Because in Julia `<` uses lexicographic comparisons on vectors, `@orderby(df, :b)` will actually do something. The thing to compare doesn't need to be a scalar. This is pretty unintuitive behavior for me at least. 

3. The `@orderby` code was written 6(!!!) years ago. I hardly understand it and I think it could be re-written in a more maintainable way. 

4. You will notice that none of the macros in DataFramesMeta actually allow keyword arguments, even if they look like they do. (try doing `transform(df; y = :x)`). This is because Julia puts keyword arguments in the *front* of the syntax tree for a call, rather than at the end, so things like `x.args[1]` break. 

In general I would be against keyword arguments in things like `@transform` because that would confuse the user. Is it a new column or a keyword argument? But in `@orderby` this seems fine because there is no pseudo-keyword argument syntax. 

Consequently I propose the following

1. Develop an infrastructure for adding parsing keyword arguments. What I would like is a struct with two fields, one with main arguments and one with the keyword arguments. That way we can apply existing `replace_syms!` recursive stuff on the first one and change behavior using the second one. 
1. Deprecate `@orderby` for an `AbstractDataFrame`. 
2. Implement a `@sort` macro which takes over the same behavior for an `AbstractDataFrame`
3. re-write `@orderby` to keep up with modern Julia idioms.

**Comment by pdeffebach** [comment]
Paging @bkamins on this issue. 

Are there any recent developments in DataFrames that would make this easy to implement in DataFramesMeta? 

I had forgotten about this but want to get it sorted out between 1.0.

**Comment by bkamins** [comment]
Currently `sort` is not worked on in DataFrames.jl. I personally think that its API is not super clean, but changing it now would be too breaking. What do you need from DataFrames.jl to move forward with changes in DataFramesMeta.jl?

**Comment by pdeffebach** [comment]
Looking at the docs for `order` now, I think what we need is an `order` function that accepts `AbstractVector`s. This is probably beyond the scope of DataFrames. 

I don't want to add keyword arguments because that's a whole other can of worms. Something like 

```
df = DataFrame(a = [1, 2], b = ["x", "y"])
@orderby(df, order("1" .* :b, rev = true))
```

**Comment by bkamins** [comment]
> I think what we need is an `order` function that accepts `AbstractVectors`

you mean to allow to pass vectors not present in a data frame. I would use then use `sortperm` and pass to it an appropriate transformation (you can hide it "under the hood" of `@order`)

**Comment by pdeffebach** [comment]
Ah good

I think this is an appropriate solution

```
julia> df = DataFrame(a = [1, 2], b = ["x", "y"])
2×2 DataFrame
 Row │ a      b      
     │ Int64  String 
─────┼───────────────
   1 │     1  x
   2 │     2  y

julia> @orderby(df, sortperm(:b, rev = true))
2×2 DataFrame
 Row │ a      b      
     │ Int64  String 
─────┼───────────────
   1 │     2  y
   2 │     1  x
```

I will close, I think this is as good a solution as I can make.

**Comment by nalimilan** [comment]
Should `@orderby` be replaced with `@sort` BTW? That would be more consistent with DataFrames.

**Comment by pdeffebach** [comment]
I would say not yet, given there isn't a `sort(df, src => fun)` function in DataFrames currently.

**Comment by nalimilan** [comment]
Ah right. Though the current implementation for `@orderby` is probably equivalent to what we would implement in DataFrames.
