### ISSUE TITLE
Can we separate out `@linq` into separate package?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFramesMeta.jl#173]
The `@linq` macro is just extra noise that takes away focus on the core macros.

Would it make sense to separate it out to a `DataFramesMetaLinq.jl`? So user can import it if they want, and this lessens the maintenance burden on DataFramesMeta.jl

**Comment by pdeffebach** [comment]
Thanks for the issue file. 

I agree that `@linq` is a pain. It's currently holding up #171 because of it's odd mix of macro evaluation and normal parsing. 

However I think that we should decide to either deprecate it or keep it in the same package. The implementation of `@linq` is so tightly knit together with the rest of DataFramesMeta that having it in a separate package would make it very hard to test and maintain. For instance, I would have never caught bugs related to #171 and #163 without `@linq` being included in the test suite. 

If we think `@pipe` is enough, then I would be okay deprecating. But my sense is that people really like `@linq` because it lets them avoid typing `_,` every time.

**Comment by pdeffebach** [comment]
As an additional update, `@linq` was never causing a problem in #171. I was mistaken because I had made a mistake while writing the tests.

**Comment by xiaodaigh** [comment]
> deprecate it

I vote for this. It's a standalone thing and doesn't compose with anything else.

**Comment by pdeffebach** [comment]
Closed, since we now prefer `@chain`.
