### ISSUE TITLE
Consider re-naming this package`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#175]
DataFramesMeta is not a very clear name to new users. "Meta" means metaprogramming in this context, of course, but it's not clear form the name. 

Alternatives: DataFramesMacros?

**Comment by bkamins** [comment]
I know it was a raised issue, but on the other hand DataFramesMeta.jl is a long established name.

**Comment by pdeffebach** [comment]
Yes, I think that it would make this package harder to discover and a lot of people would be downloading a no-longer-supported package if we rename.

**Comment by jmboehm** [comment]
There is https://github.com/matthieugomez/DataFramesMacros.jl. Conceptually, the separation between the two packages is not clear to me, as both packages seem to provide convenience macros that do not impose a particular 'ideology' on how to use DataFrames (in contrast to, say, Query.jl and Douglass.jl)-- except for the LINQ macro.

You're right about the fact that rename the package would break a lot of existing references to it. My sense is that the current user base of Julia's data ecosystem is only a fraction of what it could be, so my preference would be to 'do it right for the long term'. But I see the counterargument.

**Comment by pdeffebach** [comment]
My impression is that everything in DataFramesMacros.jl will be incorporated into DataFramesMeta in the near-term. We already have a `@cols` macro that has not been exposed to the user. A `@rows` macro will be added soon. 

Right now the package is an interesting experiment in testing out use `x` instead of `:x` inside these macros to refer to column names. I guess it's a bit unfortunate that this package is sitting on such prime namespace, but it's not big deal. 

I will leave this issue open for now as a place to discuss further. I see your point about the right thing "long term". I will think on this more.

**Comment by CameronBieganek** [comment]
I agree that DataFramesMacros.jl would probably be a better name in the long run.

**Comment by tk3369** [comment]
There's also JuliaDBMeta which probably got the naming idea from this package 😉

**Comment by matthieugomez** [comment]
+1 for DataFramesMacros (This is the main reason I have not registered it yet)

**Comment by pdeffebach** [comment]
Marking this as Decision 1.0. 

But this package has a lot of users and i think I don't think it would be best to change at this point in time.

**Comment by bkamins** [comment]
I would be OK with staying with the current name.

**Comment by ym-han** [comment]
For those of you who prefer 'DataFrameMacros' / 'DataFramesMacros': why's that? 

I personally suspect that there won't be much of a difference between 'Macros' and 'Meta' for new users (though I'm not sure; it's an empirical question). I can see how 'Macros' might seem more descriptive (Wikipedia says: "Macros are used to make a sequence of computing instructions available to the programmer as a single program statement, making the programming task less tedious and less error-prone"). But I'm not sure how much more descriptive 'Macros' really would be than 'Meta' for the sorts of people who don't know much CS / don't do that much computing (I'm thinking, e.g., of a Biostats professor I had last semester who had to reach for his mouse and click his way to the appropriate menu item in RStudio every time he wanted to undo something). And the sorts of folks for whom it would be much more descriptive are likely to be able to find the package anyway.

This is obviously just armchair speculation; I'm raising it only because I think it's worth pointing out that it's not actually obvious (imo) that 'Macros' is more newbie-friendly.

**Comment by CameronBieganek** [comment]
@ym-han There is now a different registered package called DataFrameMacros, so it's a bit of a moot point now.

https://github.com/jkrumbiegel/DataFrameMacros.jl

**Comment by bkamins** [comment]
@pdeffebach - I would close this issue.
